### ISSUE TITLE
QUALIFY 키워드와 오른쪽 정렬 규칙

### ISSUE THREAD

**Issue by heoh** [jaypark72/bigquery_style_guide#3]
안녕하세요, BigQuery Style Guide를 개인적으로 적용해보다가 궁금한 것이 있어 이슈로 남깁니다.

현재 [공통 스타일 가이드 (common style guide)](https://github.com/jaypark72/bigquery_style_guide#%EA%B3%B5%ED%86%B5-%EC%8A%A4%ED%83%80%EC%9D%BC-%EA%B0%80%EC%9D%B4%EB%93%9C-common-style-guide)에는 다음과 같이 오른쪽 정렬을 권장하고 있습니다.

> 문장(statement)의 각 절(clause)은 새로운 라인에서 시작하며 각 절의 시작 키워드가 오른쪽 정렬이 되도록 한다.

BigQuery에 최근 [QUALIFY 절](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#qualify_clause)이 추가되었는데, `QUALIFY`는 기존에 가장 긴 키워드였던 `SELECT`보다 더 깁니다.
이로 인해 `QUALIFY` 키워드가 들어간 문장은 다른 절들을 `QUALIFY`에 맞게 모든 키워드를 오른쪽 정렬을 하는 것이 번거롭게 느껴집니다.

쿼리가 수정되는 경우에 정렬로 인한 불필요한 diff가 생기는 문제도 발생하고요.

혹시 좋은 방법이 있을까요?

**Comment by jaypark72** [comment]
안녕하세요,  말씀하신대로  `QUALIFY` 키워드가 가이드 작성 이후에 추가되어 아래와 같이 right align 에 이슈가 생기긴 했습니다.

EX. 정렬이 어긋나는 경우의 예시 - pseudo code
```sql
SELECT * 
  FROM base_table
 WHERE TRUE
QUALITY ROW_NUMBER() OVER (PARTITION BY ... ORDER BY created_dt DESC) = 1
```

다만, 사내에서 작성된 쿼리들을 리뷰해 보면 메인쿼리가 `QUALIFY` 로 마무리되는 경우는 극히 드물고 서브쿼리에서 중복제거를 위해 `ROW_NUMBER()`와 함께 쓰이는 경우가 많아 대부분의 쿼리들이 `WITH`와 함께 아래의 형태로 작성되고 있어 크게 문제 되지는 않고 있습니다.

EX. CTE 구문에서 QUALIFY를 사용한 예시 - pseudo code
```sql
WITH dedup AS (
  SELECT * 
    FROM base_table
   WHERE TRUE
 QUALITY ROW_NUMBER() OVER (PARTITION BY ... ORDER BY created_dt DESC) = 1
)
-- Main Query
SELECT * 
  FROM dedup
  JOIN other_thable ON ...
;
```

이 방식은 작성하는 로직에 따라서 CTE 서브쿼리를 사용하지 않을 수도 있어서 모든 상황에 적용 가능해 보이지는 않습니다.

이미 작성되어 있는 쿼리 스타일에 변경을 주지 않고 `QUALIFY`절을 추가하고자 한다면 당장은 `QUALIFY` 절을 줄바꿈 하지 않고 WHERE 조건식이 나오는 곳에 위치시키는 것이 최선이 아닐까 싶습니다.  

```sql
  SELECT * 
    FROM base_table
   WHERE TRUE QUALITY ROW_NUMBER() OVER (PARTITION BY ... ORDER BY created_dt DESC) = 1
```
또는 이미 `WHERE` 절에 조건이 있는 경우 `AND TRUE` 와 함께 아래와 같이 작성 가능할 것 같습니다.
```sql
  SELECT * 
    FROM base_table
   WHERE col1 IS NOT NULL
     AND TRUE QUALITY ROW_NUMBER() OVER (PARTITION BY ... ORDER BY created_dt DESC) = 1
```
*QUALIFY가 WHERE절을 반드시 필요로 하기 때문에 이를 이용한 약간의 트릭입니다.

내용 참고 부탁드리고 큰 도움이 되지 못해 죄송합니다.

**Comment by heoh** [comment]
저에겐 어려운 문제였는데 조언이 많은 도움이 되었습니다.
답변해주셔서 감사합니다.

**Comment by jaypark72** [comment]
(update) QUALIFY가 GA된 이후로 WHERE 절을 요구하는 제약은 없습니다.
